use gtdb2_devel
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW seq_info_prefix_view AS
SELECT
	seq_info_id as seq_info_seq_info_id,
	molar_concentration as seq_info_molar_concentration,
	molar_concentration_device_id as seq_info_molar_concentration_device_id,
	fragment_length as seq_info_fragment_length,
	fragment_length_device_id as seq_info_fragment_length_device_id,
	seq_state_category_id as seq_info_seq_state_category_id,
	seq_type_category_id as seq_info_seq_type_category_id,
	seq_application_category_id as seq_info_seq_application_category_id
FROM seq_info

