
USE GTDB2_practice
GO

-- Use this command to get a script to grant execute for all database objects
--SELECT 'GRANT EXECUTE ON ' + name + ' TO chiasmauser'
--FROM sys.all_objects
--WHERE is_ms_shipped = 0
--AND (type = 'P' or type = 'FN')
--ORDER BY name

-- test 11


GRANT EXECUTE ON fComplement TO chiasmauser
GRANT EXECUTE ON fDeNormAlleleVariant_NoFlip TO chiasmauser
GRANT EXECUTE ON fDetermineTopBot TO chiasmauser
GRANT EXECUTE ON fGetAuthorityId TO chiasmauser
GRANT EXECUTE ON fHWChi2 TO chiasmauser
GRANT EXECUTE ON fn_diagramobjects TO chiasmauser
GRANT EXECUTE ON fPolarizeAlleleResult TO chiasmauser
GRANT EXECUTE ON fPolarizeAlleleVariant TO chiasmauser
GRANT EXECUTE ON fTopPolarizeAlleleResult TO chiasmauser
GRANT EXECUTE ON fTopPolarizeAlleleVariant TO chiasmauser
GRANT EXECUTE ON p_AddPrimerToAssay TO chiasmauser
GRANT EXECUTE ON p_BulkQCGetGenotypes TO chiasmauser
GRANT EXECUTE ON p_BulkQCGetIndividuals TO chiasmauser
GRANT EXECUTE ON p_BulkQCGetMarkers TO chiasmauser
GRANT EXECUTE ON p_BulkQCGetSamples TO chiasmauser
GRANT EXECUTE ON p_CreateAssay TO chiasmauser
GRANT EXECUTE ON p_CreateAssayMapping TO chiasmauser
GRANT EXECUTE ON p_CreateBeadChip TO chiasmauser
GRANT EXECUTE ON p_CreateBeadChipType TO chiasmauser
GRANT EXECUTE ON p_CreateBlankIndividual TO chiasmauser
GRANT EXECUTE ON p_CreateContact TO chiasmauser
GRANT EXECUTE ON p_CreateContactCategory TO chiasmauser
GRANT EXECUTE ON p_CreateContactMapping TO chiasmauser
GRANT EXECUTE ON p_CreateContainer TO chiasmauser
GRANT EXECUTE ON p_CreateDevice TO chiasmauser
GRANT EXECUTE ON p_CreateExternalBarcode TO chiasmauser
GRANT EXECUTE ON p_CreateFlowCell TO chiasmauser
GRANT EXECUTE ON p_CreateFlowCellDisc TO chiasmauser
GRANT EXECUTE ON p_CreateFlowCellWell TO chiasmauser
GRANT EXECUTE ON p_CreateGenotype TO chiasmauser
GRANT EXECUTE ON p_CreateIndividual TO chiasmauser
GRANT EXECUTE ON p_CreateInternalBarcode TO chiasmauser
GRANT EXECUTE ON p_CreateInternalReport TO chiasmauser
GRANT EXECUTE ON p_CreateMarker TO chiasmauser
GRANT EXECUTE ON p_CreateMarkerMapping TO chiasmauser
GRANT EXECUTE ON p_CreateNegSample TO chiasmauser
GRANT EXECUTE ON p_CreatePlate TO chiasmauser
GRANT EXECUTE ON p_CreatePlateDilutionScheme TO chiasmauser
GRANT EXECUTE ON p_CreatePlateType TO chiasmauser
GRANT EXECUTE ON p_CreatePrimer TO chiasmauser
GRANT EXECUTE ON p_CreateProject TO chiasmauser
GRANT EXECUTE ON p_CreateProjectGroup TO chiasmauser
GRANT EXECUTE ON p_CreateProjectMapping TO chiasmauser
GRANT EXECUTE ON p_CreateResultPlate TO chiasmauser
GRANT EXECUTE ON p_CreateResultPlateMapping TO chiasmauser
GRANT EXECUTE ON p_CreateSample TO chiasmauser
GRANT EXECUTE ON p_CreateSampleMapping TO chiasmauser
GRANT EXECUTE ON p_CreateSampleSeries TO chiasmauser
GRANT EXECUTE ON p_CreateSampleSeriesGroup TO chiasmauser
GRANT EXECUTE ON p_CreateSampleSeriesMapping TO chiasmauser
GRANT EXECUTE ON p_CreateSpecies TO chiasmauser
GRANT EXECUTE ON p_CreateState TO chiasmauser
GRANT EXECUTE ON p_CreateTube TO chiasmauser
GRANT EXECUTE ON p_CreateTubeRackType TO chiasmauser
GRANT EXECUTE ON p_CreateUser TO chiasmauser
GRANT EXECUTE ON p_CreateUserGroup TO chiasmauser
GRANT EXECUTE ON p_CreateUserMapping TO chiasmauser
GRANT EXECUTE ON p_CreateWorkingSet TO chiasmauser
GRANT EXECUTE ON p_DeleteAliquot TO chiasmauser
GRANT EXECUTE ON p_DeleteAssayMapping TO chiasmauser
GRANT EXECUTE ON p_DeleteBeadChip TO chiasmauser
GRANT EXECUTE ON p_DeleteContactMapping TO chiasmauser
GRANT EXECUTE ON p_DeleteContainer TO chiasmauser
GRANT EXECUTE ON p_DeleteFlowCell TO chiasmauser
GRANT EXECUTE ON p_DeleteIndividual TO chiasmauser
GRANT EXECUTE ON p_DeleteInternalReport TO chiasmauser
GRANT EXECUTE ON p_DeleteMarkerMapping TO chiasmauser
GRANT EXECUTE ON p_DeletePlate TO chiasmauser
GRANT EXECUTE ON p_DeleteProjectGroup TO chiasmauser
GRANT EXECUTE ON p_DeleteProjectMapping TO chiasmauser
GRANT EXECUTE ON p_DeleteResultPlate TO chiasmauser
GRANT EXECUTE ON p_DeleteResultPlateMapping TO chiasmauser
GRANT EXECUTE ON p_DeleteSample TO chiasmauser
GRANT EXECUTE ON p_DeleteSampleMapping TO chiasmauser
GRANT EXECUTE ON p_DeleteSampleSeriesGroup TO chiasmauser
GRANT EXECUTE ON p_DeleteSampleSeriesMapping TO chiasmauser
GRANT EXECUTE ON p_DeleteState TO chiasmauser
GRANT EXECUTE ON p_DeleteTube TO chiasmauser
GRANT EXECUTE ON p_DeleteUserGroup TO chiasmauser
GRANT EXECUTE ON p_DeleteUserMapping TO chiasmauser
GRANT EXECUTE ON p_DisposeGenericContainer TO chiasmauser
GRANT EXECUTE ON p_ExistFlowCellsInProject TO chiasmauser
GRANT EXECUTE ON p_ExportGenotypesGetGenotypesForInternalReport TO chiasmauser
GRANT EXECUTE ON p_ExportGenotypesGetIndividualsSelected TO chiasmauser
GRANT EXECUTE ON p_ExportGenotypesGetMarkersForInternalReport TO chiasmauser
GRANT EXECUTE ON p_ExportGenotypesGetMarkersSelected TO chiasmauser
GRANT EXECUTE ON p_GetAliquotHistory TO chiasmauser
GRANT EXECUTE ON p_GetAliquots TO chiasmauser
GRANT EXECUTE ON p_GetAliquotsForSample TO chiasmauser
GRANT EXECUTE ON p_GetAliquotsForSourceContainer TO chiasmauser
GRANT EXECUTE ON p_GetAlleleResults TO chiasmauser
GRANT EXECUTE ON p_GetAlleleVariants TO chiasmauser
GRANT EXECUTE ON p_GetAssayById TO chiasmauser
GRANT EXECUTE ON p_GetAssayByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetAssayHistory TO chiasmauser
GRANT EXECUTE ON p_GetAssaysByIdentifierFilter TO chiasmauser
GRANT EXECUTE ON p_GetAssaysForMarker TO chiasmauser
GRANT EXECUTE ON p_GetAssaysForWorkingSet TO chiasmauser
GRANT EXECUTE ON p_GetAssayWorkingSetHistory TO chiasmauser
GRANT EXECUTE ON p_GetBeadChipByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetBeadChipHistory TO chiasmauser
GRANT EXECUTE ON p_GetBeadChipLabels TO chiasmauser
GRANT EXECUTE ON p_GetBeadChipsForPlate TO chiasmauser
GRANT EXECUTE ON p_GetBeadChipsForSample TO chiasmauser
GRANT EXECUTE ON p_GetBeadChipTypes TO chiasmauser
GRANT EXECUTE ON p_GetBeadChipWellHistory TO chiasmauser
GRANT EXECUTE ON p_GetBeadChipWells TO chiasmauser
GRANT EXECUTE ON p_GetBlankSamplesForSampleSeries TO chiasmauser
GRANT EXECUTE ON p_GetColumnLength TO chiasmauser
GRANT EXECUTE ON p_GetContactCategories TO chiasmauser
GRANT EXECUTE ON p_GetContactCategory TO chiasmauser
GRANT EXECUTE ON p_GetContactMapping TO chiasmauser
GRANT EXECUTE ON p_GetContacts TO chiasmauser
GRANT EXECUTE ON p_GetContainerContentsHistory TO chiasmauser
GRANT EXECUTE ON p_GetContainerHistory TO chiasmauser
GRANT EXECUTE ON p_GetContainerMoveHistory TO chiasmauser
GRANT EXECUTE ON p_GetContainerPath TO chiasmauser
GRANT EXECUTE ON p_GetContainersTopLevel TO chiasmauser
GRANT EXECUTE ON p_GetControlTubes TO chiasmauser
GRANT EXECUTE ON p_GetDevices TO chiasmauser
GRANT EXECUTE ON p_GetDiluteHistoryFromContainer TO chiasmauser
GRANT EXECUTE ON p_GetDiluteHistoryFromWell TO chiasmauser
GRANT EXECUTE ON p_GetDiluteHistoryToPlate TO chiasmauser
GRANT EXECUTE ON p_GetDiluteHistoryToWell TO chiasmauser
GRANT EXECUTE ON p_GetFlowCellByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetFlowCellDiscsForProject TO chiasmauser
GRANT EXECUTE ON p_GetFlowCellHistory TO chiasmauser
GRANT EXECUTE ON p_GetFlowCellMappingForProject TO chiasmauser
GRANT EXECUTE ON p_GetFlowCellWellDiscLinkHistory TO chiasmauser
GRANT EXECUTE ON p_GetFlowCellWellHistory TO chiasmauser
GRANT EXECUTE ON p_GetFlowCellWells TO chiasmauser
GRANT EXECUTE ON p_GetGenericContainerByBarcode TO chiasmauser
GRANT EXECUTE ON p_GetGenericContainerById TO chiasmauser
GRANT EXECUTE ON p_GetGenericContainerByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetGenericContainerContents TO chiasmauser
GRANT EXECUTE ON p_GetGenericContainers TO chiasmauser
GRANT EXECUTE ON p_GetGenericContainersAdvancedSearch TO chiasmauser
GRANT EXECUTE ON p_GetGenericContainersByIdentifierFilter TO chiasmauser
GRANT EXECUTE ON p_GetGenericContainersForSampleSeries TO chiasmauser
GRANT EXECUTE ON p_GetGenericContainersUncontained TO chiasmauser
GRANT EXECUTE ON p_GetGenericMasterContainers TO chiasmauser
GRANT EXECUTE ON p_GetGenotypeStatuses TO chiasmauser
GRANT EXECUTE ON p_GetGtMethodById TO chiasmauser
GRANT EXECUTE ON p_GetGtMethodByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetGtMethods TO chiasmauser
GRANT EXECUTE ON p_GetIndividualById TO chiasmauser
GRANT EXECUTE ON p_GetIndividualByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetIndividualHistory TO chiasmauser
GRANT EXECUTE ON p_GetIndividualsByIdentifierFilter TO chiasmauser
GRANT EXECUTE ON p_GetIndividualsChildren TO chiasmauser
GRANT EXECUTE ON p_GetIndividualsForInternalReport TO chiasmauser
GRANT EXECUTE ON p_GetIndividualsForPlate TO chiasmauser
GRANT EXECUTE ON p_GetInternalReportById TO chiasmauser
GRANT EXECUTE ON p_GetInternalReportByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetInternalReportHistory TO chiasmauser
GRANT EXECUTE ON p_GetInternalReportHistoryForProject TO chiasmauser
GRANT EXECUTE ON p_GetInternalReportIndividualStatistics TO chiasmauser
GRANT EXECUTE ON p_GetInternalReportMarkerStatistics TO chiasmauser
GRANT EXECUTE ON p_GetInternalReportsForProject TO chiasmauser
GRANT EXECUTE ON p_GetItem TO chiasmauser
GRANT EXECUTE ON p_GetMarkerById TO chiasmauser
GRANT EXECUTE ON p_GetMarkerByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetMarkerDetails TO chiasmauser
GRANT EXECUTE ON p_GetMarkerHistory TO chiasmauser
GRANT EXECUTE ON p_GetMarkersByIdentifierFilter TO chiasmauser
GRANT EXECUTE ON p_GetMarkersForWorkingSet TO chiasmauser
GRANT EXECUTE ON p_GetMarkerWorkingSetHistory TO chiasmauser
GRANT EXECUTE ON p_GetPlateById TO chiasmauser
GRANT EXECUTE ON p_GetPlateByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetPlateDilutionSchemes TO chiasmauser
GRANT EXECUTE ON p_GetPlateDilutionWells TO chiasmauser
GRANT EXECUTE ON p_GetPlateHistory TO chiasmauser
GRANT EXECUTE ON p_GetPlateLabels TO chiasmauser
GRANT EXECUTE ON p_GetPlates TO chiasmauser
GRANT EXECUTE ON p_GetPlateTypes TO chiasmauser
GRANT EXECUTE ON p_GetPrimerById TO chiasmauser
GRANT EXECUTE ON p_GetPrimerByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetPrimerHistory TO chiasmauser
GRANT EXECUTE ON p_GetPrimersByIdentifierFilter TO chiasmauser
GRANT EXECUTE ON p_GetPrimerSetHistoryForAssay TO chiasmauser
GRANT EXECUTE ON p_GetPrimerSetHistoryForPrimer TO chiasmauser
GRANT EXECUTE ON p_GetPrimersForAssay TO chiasmauser
GRANT EXECUTE ON p_GetPrimerTypes TO chiasmauser
GRANT EXECUTE ON p_GetProjectGroup TO chiasmauser
GRANT EXECUTE ON p_GetProjectGroups TO chiasmauser
GRANT EXECUTE ON p_GetProjectHistory TO chiasmauser
GRANT EXECUTE ON p_GetProjectMapping TO chiasmauser
GRANT EXECUTE ON p_GetProjectRightsHistoryForProject TO chiasmauser
GRANT EXECUTE ON p_GetProjectRightsHistoryForUser TO chiasmauser
GRANT EXECUTE ON p_GetProjects TO chiasmauser
GRANT EXECUTE ON p_GetProjectSampleSeriesHistoryForProject TO chiasmauser
GRANT EXECUTE ON p_GetProjectSampleSeriesHistoryForSampleSeries TO chiasmauser
GRANT EXECUTE ON p_GetProjectsByIdentifierFilter TO chiasmauser
GRANT EXECUTE ON p_GetProjectsForFlowCellDisc TO chiasmauser
GRANT EXECUTE ON p_GetProjectsForFlowCellWell TO chiasmauser
GRANT EXECUTE ON p_GetProjectsForUser TO chiasmauser
GRANT EXECUTE ON p_GetQualityControlDatabases TO chiasmauser
GRANT EXECUTE ON p_GetResultPlateByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetResultPlateHistory TO chiasmauser
GRANT EXECUTE ON p_GetResultPlatesForInternalReport TO chiasmauser
GRANT EXECUTE ON p_GetResultPlatesForProject TO chiasmauser
GRANT EXECUTE ON p_GetResultPlatesForSample TO chiasmauser
GRANT EXECUTE ON p_GetResultPlatesForWorkingSet TO chiasmauser
GRANT EXECUTE ON p_GetResultPlateWorkingSetHistory TO chiasmauser
GRANT EXECUTE ON p_GetSampleById TO chiasmauser
GRANT EXECUTE ON p_GetSampleByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetSampleHistory TO chiasmauser
GRANT EXECUTE ON p_GetSamplesByIdentifierFilter TO chiasmauser
GRANT EXECUTE ON p_GetSampleSeries TO chiasmauser
GRANT EXECUTE ON p_GetSampleSeriesForUser TO chiasmauser
GRANT EXECUTE ON p_GetSampleSeriesGroup TO chiasmauser
GRANT EXECUTE ON p_GetSampleSeriesGroups TO chiasmauser
GRANT EXECUTE ON p_GetSampleSeriesHistory TO chiasmauser
GRANT EXECUTE ON p_GetSampleSeriesMapping TO chiasmauser
GRANT EXECUTE ON p_GetSampleSeriesRightsHistoryForSampleSeries TO chiasmauser
GRANT EXECUTE ON p_GetSampleSeriesRightsHistoryForUser TO chiasmauser
GRANT EXECUTE ON p_GetSamplesForIndividual TO chiasmauser
GRANT EXECUTE ON p_GetSamplesForPlate TO chiasmauser
GRANT EXECUTE ON p_GetSamplesForSampleSeries TO chiasmauser
GRANT EXECUTE ON p_GetSamplesForWorkingSet TO chiasmauser
GRANT EXECUTE ON p_GetSampleWorkingSetHistory TO chiasmauser
GRANT EXECUTE ON p_GetSexes TO chiasmauser
GRANT EXECUTE ON p_GetSpecies TO chiasmauser
GRANT EXECUTE ON p_GetStateById TO chiasmauser
GRANT EXECUTE ON p_GetStateByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetStateIsUsed TO chiasmauser
GRANT EXECUTE ON p_GetStates TO chiasmauser
GRANT EXECUTE ON p_GetTubeById TO chiasmauser
GRANT EXECUTE ON p_GetTubeByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetTubeHistory TO chiasmauser
GRANT EXECUTE ON p_GetTubeRackLabels TO chiasmauser
GRANT EXECUTE ON p_GetTubeRackTypes TO chiasmauser
GRANT EXECUTE ON p_GetUserCurrent TO chiasmauser
GRANT EXECUTE ON p_GetUserGroup TO chiasmauser
GRANT EXECUTE ON p_GetUserGroups TO chiasmauser
GRANT EXECUTE ON p_GetUserHistory TO chiasmauser
GRANT EXECUTE ON p_GetUserMapping TO chiasmauser
GRANT EXECUTE ON p_GetUsers TO chiasmauser
GRANT EXECUTE ON p_GetWorkingSetByIdentifier TO chiasmauser
GRANT EXECUTE ON p_GetWorkingSets TO chiasmauser
GRANT EXECUTE ON p_MoveContainer TO chiasmauser
GRANT EXECUTE ON p_QCBacksync TO chiasmauser
GRANT EXECUTE ON p_QCCleanDeletedPlates TO chiasmauser
GRANT EXECUTE ON p_QCInsertWsetOffset TO chiasmauser
GRANT EXECUTE ON p_QCRebuildAll TO chiasmauser
GRANT EXECUTE ON p_QCRebuildDatabase TO chiasmauser
GRANT EXECUTE ON p_QCRefreshProject TO chiasmauser
GRANT EXECUTE ON p_QCReset TO chiasmauser
GRANT EXECUTE ON p_RestoreGenericContainer TO chiasmauser
GRANT EXECUTE ON p_SetFlowCellDiscToProject TO chiasmauser
GRANT EXECUTE ON p_UpdateAliquot TO chiasmauser
GRANT EXECUTE ON p_UpdateAliquotComment TO chiasmauser
GRANT EXECUTE ON p_UpdateAliquotConcentration TO chiasmauser
GRANT EXECUTE ON p_UpdateAliquotVolume TO chiasmauser
GRANT EXECUTE ON p_UpdateAssayComment TO chiasmauser
GRANT EXECUTE ON p_UpdateBeadChip TO chiasmauser
GRANT EXECUTE ON p_UpdateBeadChipWell TO chiasmauser
GRANT EXECUTE ON p_UpdateContact TO chiasmauser
GRANT EXECUTE ON p_UpdateContactCategory TO chiasmauser
GRANT EXECUTE ON p_UpdateContainer TO chiasmauser
GRANT EXECUTE ON p_UpdateFlowCell TO chiasmauser
GRANT EXECUTE ON p_UpdateFlowCellWell TO chiasmauser
GRANT EXECUTE ON p_UpdateFlowCellWellDiscLink TO chiasmauser
GRANT EXECUTE ON p_UpdateIndividual TO chiasmauser
GRANT EXECUTE ON p_UpdateIndividualParent TO chiasmauser
GRANT EXECUTE ON p_UpdateInternalReport TO chiasmauser
GRANT EXECUTE ON p_UpdateInternalReportMarkerComment TO chiasmauser
GRANT EXECUTE ON p_UpdateMarkerComment TO chiasmauser
GRANT EXECUTE ON p_UpdatePlate TO chiasmauser
GRANT EXECUTE ON p_UpdatePrimerComment TO chiasmauser
GRANT EXECUTE ON p_UpdatePrimerCommentAndOrientation TO chiasmauser
GRANT EXECUTE ON p_UpdateProject TO chiasmauser
GRANT EXECUTE ON p_UpdateProjectGroup TO chiasmauser
GRANT EXECUTE ON p_UpdateSample TO chiasmauser
GRANT EXECUTE ON p_UpdateSampleComment TO chiasmauser
GRANT EXECUTE ON p_UpdateSampleConcentrationCurrent TO chiasmauser
GRANT EXECUTE ON p_UpdateSampleConcentrationCustomer TO chiasmauser
GRANT EXECUTE ON p_UpdateSampleNoContainer TO chiasmauser
GRANT EXECUTE ON p_UpdateSampleSeriesGroup TO chiasmauser
GRANT EXECUTE ON p_UpdateSampleWithPlate TO chiasmauser
GRANT EXECUTE ON p_UpdateSampleWithTube TO chiasmauser
GRANT EXECUTE ON p_UpdateSampleVolumeCurrent TO chiasmauser
GRANT EXECUTE ON p_UpdateSampleVolumeCustomer TO chiasmauser
GRANT EXECUTE ON p_UpdateState TO chiasmauser
GRANT EXECUTE ON p_UpdateTube TO chiasmauser
GRANT EXECUTE ON p_UpdateUser TO chiasmauser
GRANT EXECUTE ON p_UpdateUserGroup TO chiasmauser
GRANT EXECUTE ON p_UpdateUserInactivate TO chiasmauser
GRANT EXECUTE ON p_UpdateWorkingSetComment TO chiasmauser
GRANT EXECUTE ON sp_alterdiagram TO chiasmauser
GRANT EXECUTE ON sp_creatediagram TO chiasmauser
GRANT EXECUTE ON sp_dropdiagram TO chiasmauser
GRANT EXECUTE ON sp_helpdiagramdefinition TO chiasmauser
GRANT EXECUTE ON sp_helpdiagrams TO chiasmauser
GRANT EXECUTE ON sp_renamediagram TO chiasmauser
GRANT EXECUTE ON sp_upgraddiagrams TO chiasmauser
